export {default as Home } from './Home'
export {default as Navbar } from './Navbar'
export {default as About } from './About'
export {default as Mynotes } from './Mynotes'
export {default as Login } from './Login'
export {default as Alert} from './Alert'